//! Generated protobuf and gRPC bindings for the Calendry solver contract.
//!
//! The `.proto` sources live in a separate, language-neutral repository
//! (`github.com/Calendry-de/calendry-proto`) because the Nuxt app consumes the
//! same contract. They are never copied into this repo — see `build.rs` for how
//! the checkout is located.

/// The `calendry.solver.v1` contract, as generated by `prost`/`tonic`.
///
/// Lints are relaxed for this module alone: everything in it is machine-written
/// from the `.proto` sources, so a lint here can only be satisfied by editing a
/// generator template in another repository. The workspace lint policy still
/// applies in full to every hand-written crate.
#[allow(
    clippy::doc_markdown,
    clippy::large_enum_variant,
    clippy::needless_pass_by_value,
    clippy::redundant_closure_for_method_calls,
    clippy::semicolon_if_nothing_returned,
    unreachable_pub,
    unused_qualifications
)]
pub mod v1 {
    tonic::include_proto!("calendry.solver.v1");
}

pub use v1::*;
